eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: API REST SERVER

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://localhost/eureka?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password:
  application:
    name: eureka-api